### ISSUE TITLE
Add e2e test for "StopCh" controls  controller shut down

### ISSUE THREAD

**Issue by dannawang0221** [kubernetes-csi/lib-volume-populator#166]
We change the "StopCh" can be passed from outside the RunControllerWithConfig https://github.com/kubernetes-csi/lib-volume-populator/pull/164 This change is hard to test with unit test, we should add e2e test to cover the change

**Comment by thisisharrsh** [comment]
Hi @dannawang0221, thank you for your contribution.

You can close this issue as the PR is also been merged.

**Comment by dannawang0221** [comment]
> Hi @dannawang0221, thank you for your contribution.
> 
> You can close this issue as the PR is also been merged.

Done
