### ISSUE TITLE
hello world installation documentation doesn't work

### ISSUE THREAD

**Issue by rwmjones** [kubernetes-csi/lib-volume-populator#42]
The documentation in https://github.com/kubernetes-csi/lib-volume-populator/tree/master/example/hello-populator seems very incomplete.  I applied the crd.yaml file and that was fine:
```
$ kubectl apply -f crd.yaml 
customresourcedefinition.apiextensions.k8s.io/hellos.hello.example.com created
```

but applying the deploy.yaml file failed:

```
$ kubectl apply -f deploy.yaml 
namespace/hello unchanged
serviceaccount/hello-account unchanged
clusterrole.rbac.authorization.k8s.io/hello-role unchanged
clusterrolebinding.rbac.authorization.k8s.io/hello-binding unchanged
deployment.apps/hello-populator unchanged
error: resource mapping not found for name: "hello-populator" namespace: "" from "deploy.yaml": no matches for kind "VolumePopulator" in version "populator.storage.k8s.io/v1beta1"
ensure CRDs are installed first
```

Could you include more compete documentation about every step you need to do to actually build and deploy the example?

**Comment by rwmjones** [comment]
This worked for me (thanks @nyoxi):

```
$ kubectl create -f https://raw.githubusercontent.com/kubernetes-csi/volume-data-source-validator/v1.0.1/client/config/crd/populator.storage.k8s.io_volumepopulators.yaml
customresourcedefinition.apiextensions.k8s.io/volumepopulators.populator.storage.k8s.io created
$ kubectl create -f https://raw.githubusercontent.com/kubernetes-csi/volume-data-source-validator/v1.0.1/deploy/kubernetes/rbac-data-source-validator.yaml
serviceaccount/volume-data-source-validator created
clusterrole.rbac.authorization.k8s.io/volume-data-source-validator created
clusterrolebinding.rbac.authorization.k8s.io/volume-data-source-validator created
$ kubectl create -f https://raw.githubusercontent.com/kubernetes-csi/volume-data-source-validator/v1.0.1/deploy/kubernetes/setup-data-source-validator.yaml
statefulset.apps/volume-data-source-validator created
$ kubectl apply -f deploy.yaml 
namespace/hello unchanged
serviceaccount/hello-account unchanged
clusterrole.rbac.authorization.k8s.io/hello-role unchanged
clusterrolebinding.rbac.authorization.k8s.io/hello-binding unchanged
deployment.apps/hello-populator unchanged
volumepopulator.populator.storage.k8s.io/hello-populator created
```

**Comment by Kartik494** [comment]
Hi @rwmjones i have tried also and got the same error as
`error: resource mapping not found for name: "hello-populator" namespace: "" from "https://raw.githubusercontent.com/kubernetes-csi/lib-volume-populator/master/example/hello-populator/deploy.yaml": no matches for kind "VolumePopulator" in version "populator.storage.k8s.io/v1beta1"
ensure CRDs are installed first`

should i need to apply separate CRD's also?

**Comment by Kartik494** [comment]
> 

I just got to know you have deployed corresponding crd's from https://github.com/kubernetes-csi/volume-data-source-validator/tree/master/client/config/crd and it worked for me but  not documented in README as you stated in the issue description so is it ok to document those crd's also?

**Comment by bswartz** [comment]
We should improve the documentation for the volume-data-source-validator, and we should mention that that project is a pre-req for this example. Alternatively, we can just modify the YAML for this example to not install the VolumePopulator object.
