### ISSUE TITLE
Populating a PVC with ReadWriteMany results in a stuck PVC

### ISSUE THREAD

**Issue by bennyz** [kubernetes-csi/lib-volume-populator#63]
We noticed an issue where using our volume populator to populate a PVC with the `ReadWriteMany` accessMode, where the populator pod will complete successfully, there will be a Bound PV, but then the PVC will revert back to Pending, causing a new instance of the populator pod to be created (which will be stuck because the prime PVC is gone at this point).

@liranr23 noticed the PV has a different accessMode, `ReadWriteOnce` which the prime PVC is also created with

```yaml
kind: PersistentVolume
apiVersion: v1
metadata:
  annotations:
    forklift.konveyor.io/populated-from: default/nfs-vol-pop
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
    volume.kubernetes.io/provisioner-deletion-secret-name: mount-options
    volume.kubernetes.io/provisioner-deletion-secret-namespace: default
  finalizers:
    - kubernetes.io/pv-protection

spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: default
    name: nfs-vol-pop
    uid: e1356dd1-bbc8-4535-bb02-2454844f55a5
    apiVersion: v1
    resourceVersion: '119290924'
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=4.1
  volumeMode: Filesystem
status:
  phase: Bound
```

And this is the PVC stuck in Pending
```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-vol-pop
  namespace: default
  uid: e1356dd1-bbc8-4535-bb02-2454844f55a5
  annotations: ...
  finalizers:
    - kubernetes.io/pvc-protection
    - forklift.konveyor.io/populate-target-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-csi
  volumeMode: Filesystem
  dataSource:
    apiGroup: forklift.konveyor.io
    kind: OvirtImageIOPopulator
    name: nfs-vol-pop
  dataSourceRef:
    apiGroup: forklift.konveyor.io
    kind: OvirtImageIOPopulator
    name: nfs-vol-pop
status:
  phase: Pending
```

So looking at the code, we see this access mode is hardcoded here
https://github.com/kubernetes-csi/lib-volume-populator/blob/a1ea5aea25c88ffbac22592fa4e9ff879f25f864/populator-machinery/controller.go#L590

Is this intentional?

Changing the line to:
```go
						AccessModes:      pvc.Spec.AccessModes,
```
Seems to fix the issue

**Comment by humblec** [comment]
@bennyz @liranr23 propagating the accessmode looks a reasonable fix to me. I dont think we have to be on RWO mandatory. One possible scenario which I can think of here to take advantage of RWO mode PVC for populator pod  is to make sure only one node access to the PVC going to be created, but then if its causing another issue this fix looks good to me. 

Cc @bswartz for thoughts.

**Comment by ahadas** [comment]
The context here is that we're about to use volume-populator in [forklift](https://www.konveyor.io/tools/forklift/) to fetch virtual disks from oVirt & Openstack, and PVCs need to be set with RWX in order to enable live-migration for the imported virtual machines

**Comment by bswartz** [comment]
Yeah this looks like an accident on my part. I think I was thinking that the populator pod itself only need RWO access, but obviously if that results in a different kind of volume that can't find to an RWX PVC, then it's a huge problem.

I can't think of any downsides to to the fix you propose, so let's try it.
